version: '3.8'
services: 
    web:
        build: .
        command: python3 /code/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password' 
            POSTGRES_DB: 'crudapi_db_1'
        ports:
            - 5432      
volumes: 
    postgres_data:          