# Generated by Django 3.1.2 on 2020-10-29 16:30

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_trigger', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('reuse', models.BooleanField(default=True)),
                ('constraint', models.CharField(max_length=250)),
                ('support_multiple', models.BooleanField(default=True)),
                ('pick_first', models.BooleanField(default=False)),
                ('var_name', models.CharField(max_length=20)),
                ('type1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='id', max_length=50), default=list, size=8)),
                ('validation_parser', models.CharField(max_length=50)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(blank=True, default=dict, null=True), blank=True, default=list, max_length=200, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='idModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_trigger', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('reuse', models.BooleanField(default=True)),
                ('support_multiple', models.BooleanField(default=True)),
                ('pick_first', models.BooleanField(default=False)),
                ('support_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=8)),
                ('type1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='id', max_length=50), default=list, size=8)),
                ('validation_parser', models.CharField(max_length=50)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(blank=True, default=dict, null=True), blank=True, default=list, max_length=200, size=None)),
            ],
        ),
    ]
